# Generated by Django 2.2.4 on 2019-10-13 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191013_1253'),
        ('accounts', '0004_auto_20191013_1444'),
    ]

    operations = [
    ]
