# Generated by Django 2.2.4 on 2019-09-22 06:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('isbn', models.CharField(max_length=255, unique=True, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('description', models.TextField(verbose_name='説明')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('published_date', models.CharField(max_length=50, verbose_name='発売日')),
                ('affiliate_url', models.URLField(max_length=2000, verbose_name='楽天ブックスURL')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wanted',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='作成日時')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('title', models.CharField(max_length=50, verbose_name='タイトル')),
                ('score', models.FloatField(verbose_name='評価')),
                ('content', models.TextField(verbose_name='本文')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
