# Generated by Django 2.2.4 on 2019-08-21 22:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('isbn', models.CharField(max_length=255, verbose_name='ISBN')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('author', models.CharField(max_length=100, verbose_name='著者')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='画像URL')),
                ('description', models.CharField(max_length=255, verbose_name='説明')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('publisher', models.CharField(max_length=100, verbose_name='出版社')),
                ('published_date', models.DateField(verbose_name='発売日')),
                ('affiliate_url', models.URLField(verbose_name='楽天ブックスURL')),
            ],
        ),
    ]
