# Generated by Django 2.2.4 on 2019-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fav_count',
            field=models.IntegerField(default=0, verbose_name='お気に入り数'),
        ),
        migrations.AddField(
            model_name='book',
            name='wanted_count',
            field=models.IntegerField(default=0, verbose_name='読みたい数'),
        ),
    ]
