# Generated by Django 2.2.4 on 2019-09-26 21:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0002_auto_20190926_0649'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'book')},
        ),
        migrations.AlterUniqueTogether(
            name='wanted',
            unique_together={('user', 'book')},
        ),
    ]
