# Generated by Django 2.2.4 on 2019-09-27 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190927_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 9, 45, 12, 528877, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 9, 45, 12, 528877, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 9, 45, 12, 528877, tzinfo=utc), verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='wanted',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 27, 9, 45, 12, 528877, tzinfo=utc), verbose_name='作成日時'),
        ),
    ]
