# Generated by Django 2.2.4 on 2019-10-08 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20190928_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-modified']},
        ),
    ]
