# Generated by Django 2.2.4 on 2019-10-26 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_auto_20191008_1546'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wanted',
        ),
    ]
