# Generated by Django 2.2.4 on 2019-10-29 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_delete_wanted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=0, verbose_name='評価'),
        ),
    ]
