# Generated by Django 2.2.4 on 2019-10-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_auto_20191029_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='score',
            field=models.FloatField(default=5, verbose_name='評価'),
        ),
    ]
